### ISSUE TITLE
add missing mountain images

### ISSUE THREAD

**Issue by cblgh** [hbshai/goraf#1]
![Løvstakken](http://i.imgur.com/2fHyOvd.png)

**Comment by smeets** [comment]
fixed?
![screenshot 2015-07-08 22 47 17](https://cloud.githubusercontent.com/assets/6011225/8581854/939912aa-25c3-11e5-991d-dbb0e087b13f.png)

**Comment by cblgh** [comment]
yes pls commit and mark as resolved
